import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { load } from 'cheerio';
import sharp from 'sharp';
import { fetch } from 'undici';
import { hexToOklch, hexToOklchTuple } from './utils/oklch.js';

const MADY_URL = 'https://mady.fr/';
const STYLESHEET_URL = 'https://madyproducts.b-cdn.net/wp-content/themes/mady/style.css';
const FAVICON_URL = 'https://madyproducts.b-cdn.net/wp-content/themes/mady/dist/images/favicon.png';

const EXPECTED_BRAND = {
  primary: '#101f2b',
  accent: '#fc4c02',
  secondary: '#00b0a1',
  surface: '#f8f6f4',
  border: '#e0e0e0',
} as const;

const BOOTSTRAP_DEFAULTS = new Set([
  '#0d6efd',
  '#198754',
  '#dc3545',
  '#ffc107',
  '#6c757d',
  '#f8f9fa',
  '#212529',
  '#495057',
  '#343a40',
  '#ced4da',
  '#adb5bd',
  '#000',
  '#000000',
  '#fff',
  '#ffffff',
]);

const HEX_PATTERN = /#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b/g;

type PaletteEntry = {
  hex: string;
  count: number;
  oklch: string;
  oklchTuple: { l: number; c: number; h: number };
};

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, {
    headers: { 'user-agent': 'mady-poc-extract-brand/1.0' },
  });
  if (!res.ok) throw new Error(`Fetch failed ${res.status} for ${url}`);
  return res.text();
}

async function fetchBuffer(url: string): Promise<Buffer> {
  const res = await fetch(url, {
    headers: { 'user-agent': 'mady-poc-extract-brand/1.0' },
  });
  if (!res.ok) throw new Error(`Fetch failed ${res.status} for ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

function normalizeHex(hex: string): string {
  const lower = hex.toLowerCase();
  if (lower.length === 4) {
    return `#${lower[1]}${lower[1]}${lower[2]}${lower[2]}${lower[3]}${lower[3]}`;
  }
  return lower;
}

function extractPalette(css: string, topN: number): PaletteEntry[] {
  const matches = css.match(HEX_PATTERN) ?? [];
  const counts = new Map<string, number>();
  for (const raw of matches) {
    const hex = normalizeHex(raw);
    if (BOOTSTRAP_DEFAULTS.has(hex)) continue;
    counts.set(hex, (counts.get(hex) ?? 0) + 1);
  }
  const sorted = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, topN);
  return sorted.map(([hex, count]) => ({
    hex,
    count,
    oklch: hexToOklch(hex),
    oklchTuple: hexToOklchTuple(hex),
  }));
}

type LogoResult = {
  source: string;
  svg: string | null;
  png: Buffer;
};

async function extractLogo(homepageHtml: string): Promise<LogoResult> {
  const $ = load(homepageHtml, { xmlMode: false });

  const headerLogo = $('.header-logo').first();
  if (headerLogo.length > 0) {
    const svgEl = headerLogo.find('svg').first();
    if (svgEl.length > 0) {
      const svgHtml = $.html(svgEl);
      const dataUriMatch = svgHtml.match(/data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)/);
      if (dataUriMatch?.[2]) {
        const png = Buffer.from(dataUriMatch[2], 'base64');
        return { source: 'inline-svg-base64', svg: svgHtml, png };
      }
    }
  }

  const fallbackSrc =
    $('img[alt*="Mady" i][src*="logo" i]').attr('src') ??
    $('img[src*="logo-mady" i]').attr('src') ??
    $('a.custom-logo-link img').attr('src');

  if (fallbackSrc) {
    const url = new URL(fallbackSrc, MADY_URL).toString();
    const buffer = await fetchBuffer(url);
    return { source: url, svg: null, png: buffer };
  }

  throw new Error('No logo candidate found on mady.fr homepage');
}

async function writeFavicons(projectRoot: string, sourcePng: Buffer): Promise<void> {
  const publicDir = path.join(projectRoot, 'public');
  await mkdir(publicDir, { recursive: true });

  await sharp(sourcePng).resize(32, 32).toFile(path.join(publicDir, 'favicon-32x32.png'));
  await sharp(sourcePng).resize(192, 192).toFile(path.join(publicDir, 'favicon-192x192.png'));
  await sharp(sourcePng).resize(512, 512).toFile(path.join(publicDir, 'favicon-512x512.png'));
  await sharp(sourcePng).resize(48, 48).toFormat('png').toFile(path.join(publicDir, 'favicon.png'));
}

function renderBrandCss(palette: PaletteEntry[]): string {
  const findByHex = (hex: string): PaletteEntry | undefined => palette.find((p) => p.hex === hex);

  const primary = findByHex(EXPECTED_BRAND.primary);
  const accent = findByHex(EXPECTED_BRAND.accent);
  const secondary = findByHex(EXPECTED_BRAND.secondary);
  const surface = findByHex(EXPECTED_BRAND.surface);
  const border = findByHex(EXPECTED_BRAND.border);

  if (!primary || !accent || !secondary) {
    throw new Error(
      `Brand colors missing from CSS. Expected ${EXPECTED_BRAND.primary}, ${EXPECTED_BRAND.accent}, ${EXPECTED_BRAND.secondary}. ` +
        `Found top: ${palette
          .slice(0, 5)
          .map((p) => p.hex)
          .join(', ')}`,
    );
  }

  return `/* Generated by scripts/extract-brand.ts — do not edit manually */
@theme {
  /* Brand — Mady identity, do not modify */
  --color-brand-primary: ${primary.hex};
  --color-brand-accent: ${accent.hex};
  --color-brand-secondary: ${secondary.hex};

  /* Neutrals */
  --color-background: #ffffff;
  --color-surface: ${surface?.hex ?? '#f8f6f4'};
  --color-foreground: ${primary.hex};
  --color-muted: #6c757d;
  --color-border: ${border?.hex ?? '#e0e0e0'};

  /* OKLCH equivalents */
  --color-brand-primary-oklch: ${primary.oklch};
  --color-brand-accent-oklch: ${accent.oklch};
  --color-brand-secondary-oklch: ${secondary.oklch};
}
`;
}

function renderReport(palette: PaletteEntry[], logoUrl: string): string {
  const rows = palette
    .map(
      (p) =>
        `| \`${p.hex}\` | ${p.count} | \`${p.oklch}\` | L ${p.oklchTuple.l} · C ${p.oklchTuple.c} · H ${p.oklchTuple.h} |`,
    )
    .join('\n');

  return `# Brand extraction report — Mady

_Auto-généré par \`scripts/extract-brand.ts\`._

## Sources

- Stylesheet : ${STYLESHEET_URL}
- Homepage : ${MADY_URL}
- Logo détecté : ${logoUrl}
- Favicon : ${FAVICON_URL}

## Palette (top ${palette.length}, defaults Bootstrap filtrés)

| Hex | Fréquence CSS | OKLCH | Composantes |
|---|---|---|---|
${rows}

## Mapping utilisé

| Rôle | Hex | Description |
|---|---|---|
| brand-primary | \`${EXPECTED_BRAND.primary}\` | Bleu nuit, texte + structures |
| brand-accent | \`${EXPECTED_BRAND.accent}\` | Orange signature, CTA + highlights |
| brand-secondary | \`${EXPECTED_BRAND.secondary}\` | Teal, catégories/certifications |
| surface | \`${EXPECTED_BRAND.surface}\` | Blanc cassé chaud, fonds secondaires |
| border | \`${EXPECTED_BRAND.border}\` | Gris clair séparateurs |

**Règle d'or** : ces couleurs ne doivent JAMAIS être modifiées. Elles sont verrouillées par assertion dans le script d'extraction (filet de sécurité contre une modification unilatérale côté mady.fr).
`;
}

async function main(): Promise<void> {
  const projectRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');

  console.warn(`→ Fetching ${STYLESHEET_URL}`);
  const css = await fetchText(STYLESHEET_URL);

  console.warn('→ Extracting palette');
  const palette = extractPalette(css, 10);
  console.warn(`  top colors: ${palette.map((p) => `${p.hex} (${p.count})`).join(', ')}`);

  console.warn(`→ Fetching ${MADY_URL}`);
  const homepage = await fetchText(MADY_URL);
  const logo = await extractLogo(homepage);
  console.warn(`  logo source: ${logo.source}`);

  const brandDir = path.join(projectRoot, 'public', 'brand');
  await mkdir(brandDir, { recursive: true });
  await writeFile(path.join(brandDir, 'logo-mady.png'), logo.png);
  if (logo.svg) {
    await writeFile(path.join(brandDir, 'logo-mady.svg'), logo.svg);
  }
  const logoUrl = logo.source;

  console.warn(`→ Fetching ${FAVICON_URL}`);
  const faviconBuf = await fetchBuffer(FAVICON_URL);
  await writeFavicons(projectRoot, faviconBuf);

  console.warn('→ Writing src/styles/brand.css');
  const stylesDir = path.join(projectRoot, 'src', 'styles');
  await mkdir(stylesDir, { recursive: true });
  await writeFile(path.join(stylesDir, 'brand.css'), renderBrandCss(palette));

  console.warn('→ Writing docs/brand-extraction.md');
  const docsDir = path.join(projectRoot, 'docs');
  await mkdir(docsDir, { recursive: true });
  await writeFile(path.join(docsDir, 'brand-extraction.md'), renderReport(palette, logoUrl));

  console.warn('✓ Brand extraction complete.');
}

main().catch((err) => {
  console.error('✗ Brand extraction failed:', err);
  process.exit(1);
});
